// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygppxuptdqfyvvdenbtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlncHB4dXB0ZHFmeXZ2ZGVuYnRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzgzOTIsImV4cCI6MjA2OTA1NDM5Mn0.YEurxYp-sPG1RyerNmUTKOMzTCpQ-hMQB5l9GjvM5aM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});